// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_button1, 100);
    lv_obj_set_height(ui_button1, 50);
    lv_obj_set_x(ui_button1, -8);
    lv_obj_set_y(ui_button1, -15);
    lv_obj_set_align(ui_button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
