// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Container1

lv_obj_t * ui_Container1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container1;
    cui_Container1 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container1);
    lv_obj_set_width(cui_Container1, 167);
    lv_obj_set_height(cui_Container1, 42);
    lv_obj_set_x(cui_Container1, -151);
    lv_obj_set_y(cui_Container1, -62);
    lv_obj_set_align(cui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(cui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_Container1);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label1, -80);
    lv_obj_set_y(cui_Label1, -4);
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "Voltage");

    lv_obj_t * cui_TextArea1;
    cui_TextArea1 = lv_textarea_create(cui_Container1);
    lv_obj_set_width(cui_TextArea1, 95);
    lv_obj_set_height(cui_TextArea1, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(cui_TextArea1, 214);
    lv_obj_set_y(cui_TextArea1, 199);
    lv_obj_set_align(cui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(cui_TextArea1, 3);
    lv_textarea_set_placeholder_text(cui_TextArea1, "Placeholder...");
    lv_textarea_set_one_line(cui_TextArea1, true);

    lv_obj_set_style_text_font(cui_TextArea1, &lv_font_montserrat_12, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER1_NUM);
    children[UI_COMP_CONTAINER1_CONTAINER1] = cui_Container1;
    children[UI_COMP_CONTAINER1_LABEL1] = cui_Label1;
    children[UI_COMP_CONTAINER1_TEXTAREA1] = cui_TextArea1;
    lv_obj_add_event_cb(cui_Container1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container1_create_hook(cui_Container1);
    return cui_Container1;
}

