// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void Hello_Animation(lv_obj_t * TargetObject, int delay);
void NoticeShow_Animation(lv_obj_t * TargetObject, int delay);
void NoticeClear_Animation(lv_obj_t * TargetObject, int delay);
void blend_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Image1;
void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
void ui_event_Power_Button(lv_event_t * e);
extern lv_obj_t * ui_Power_Button;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Setting
void ui_Setting_screen_init(void);
extern lv_obj_t * ui_Setting;
extern lv_obj_t * ui_Image6;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Label7;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label39;
// CUSTOM VARIABLES

// SCREEN: ui_Run
void ui_Run_screen_init(void);
extern lv_obj_t * ui_Run;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Label14;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Label15;
void ui_event_TextArea4(lv_event_t * e);
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Label16;
void ui_event_TextArea5(lv_event_t * e);
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Label17;
void ui_event_TextArea6(lv_event_t * e);
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label18;
void ui_event_TextArea7(lv_event_t * e);
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui_Label19;
void ui_event_TextArea8(lv_event_t * e);
extern lv_obj_t * ui_TextArea8;
extern lv_obj_t * ui_Label20;
void ui_event_TextArea9(lv_event_t * e);
extern lv_obj_t * ui_TextArea9;
extern lv_obj_t * ui_Label21;
void ui_event_TextArea10(lv_event_t * e);
extern lv_obj_t * ui_TextArea10;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Container16;
void ui_event_Container16_Container16_TextAreaLV1(lv_event_t * e);
extern lv_obj_t * ui_Container17;
void ui_event_Container17_Container17_TextAreaLOnTime1(lv_event_t * e);
extern lv_obj_t * ui_Container18;
void ui_event_Container18_Container18_TextAreaLOffTime1(lv_event_t * e);
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Label13;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label2;
void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Label9;
void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Label10;
void ui_event_Dropdown3(lv_event_t * e);
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Label11;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label12;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_left_png);    // assets/left.png
LV_IMG_DECLARE(ui_img_seting_png);    // assets/Seting.png
LV_IMG_DECLARE(ui_img_power_png);    // assets/Power.png
LV_IMG_DECLARE(ui_img_powered_png);    // assets/Powered.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/Back.png
LV_IMG_DECLARE(ui_img_backed_png);    // assets/Backed.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/Play.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets/pause.png
LV_IMG_DECLARE(ui_img_back_run_png);    // assets/back_run.png
LV_IMG_DECLARE(ui_img_back1_png);    // assets/back1.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Light);
LV_FONT_DECLARE(ui_font_Light40);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
