// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Poweroff(lv_event_t * e);
void Edit_Bri(lv_event_t * e);
void Edit_HOnT(lv_event_t * e);
void Edit_HOfT(lv_event_t * e);
void Edit_HPC(lv_event_t * e);
void Edit_HNC(lv_event_t * e);
void Edit_LOnT(lv_event_t * e);
void Edit_LOfT(lv_event_t * e);
void Edit_LPC(lv_event_t * e);
void Edit_LNC(lv_event_t * e);
void Edit_DHV(lv_event_t * e);
void Edit_DLV(lv_event_t * e);
void Edit_DHL(lv_event_t * e);
void Run_SW_PRESS(lv_event_t * e);
void PAUSE_SW_PRESS(lv_event_t * e);
void Edit_Sequence(lv_event_t * e);
void Edit_PositivePole(lv_event_t * e);
void Edit_NegativePole(lv_event_t * e);
void Edit_HV(lv_event_t * e);
void Edit_LV(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
