// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "main.h"


void Update_Para(lv_event_t *e) {
	// Your code here
	lv_label_set_text(ui_Label13, "Update Para");
}

void Edit_Bri(lv_event_t *e) {
	// Your code here
	uint8_t bri = lv_slider_get_value(ui_Slider1);
	SSD1963_SetBacklight(bri);
}

void danhaukhong(lv_event_t *e) {
//	lv_textarea_del_char(ui_comp_get_child(ui_Container3,
//	UI_COMP_CONTAINER1_TEXTAREA1));
}
