// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Run_screen_init(void)
{
    ui_Run = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Run, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_Run, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Run, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Run, LV_DIR_LEFT, 80);
    lv_obj_set_width(ui_TabView1, 580);
    lv_obj_set_height(ui_TabView1, 126);
    lv_obj_set_x(ui_TabView1, -101);
    lv_obj_set_y(ui_TabView1, 169);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabView1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_TabView1, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabView1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_TabView1), LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView1), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(lv_tabview_get_tab_btns(ui_TabView1), false,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "High Side");
    lv_obj_clear_flag(ui_TabPage1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_radius(ui_TabPage1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabPage1, lv_color_hex(0xF97A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabPage1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -160);
    lv_obj_set_y(ui_Label14, -28);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "On Time");

    ui_TextArea3 = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextArea3, 100);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_TextArea3, -60);
    lv_obj_set_y(ui_TextArea3, -28);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea3, 4);
    lv_textarea_set_placeholder_text(ui_TextArea3, "0 to 20mS");



    ui_Label15 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 76);
    lv_obj_set_y(ui_Label15, -28);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Off Time");

    ui_TextArea4 = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextArea4, 100);
    lv_obj_set_height(ui_TextArea4, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_TextArea4, 177);
    lv_obj_set_y(ui_TextArea4, -28);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea4, 4);
    lv_textarea_set_placeholder_text(ui_TextArea4, "0 to 20mS");



    ui_Label16 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -183);
    lv_obj_set_y(ui_Label16, 28);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Positive Count");

    ui_TextArea5 = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextArea5, 100);
    lv_obj_set_height(ui_TextArea5, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_TextArea5, -60);
    lv_obj_set_y(ui_TextArea5, 28);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea5, 4);
    lv_textarea_set_placeholder_text(ui_TextArea5, "0 to 20");



    ui_Label17 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 54);
    lv_obj_set_y(ui_Label17, 28);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Negative Count");

    ui_TextArea6 = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextArea6, 100);
    lv_obj_set_height(ui_TextArea6, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_TextArea6, 177);
    lv_obj_set_y(ui_TextArea6, 28);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea6, 4);
    lv_textarea_set_placeholder_text(ui_TextArea6, "0 to 20");



    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Low Side");
    lv_obj_clear_flag(ui_TabPage2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_radius(ui_TabPage2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabPage2, lv_color_hex(0x7AF986), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabPage2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -160);
    lv_obj_set_y(ui_Label18, -28);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "On Time");

    ui_TextArea7 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea7, 100);
    lv_obj_set_height(ui_TextArea7, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_TextArea7, -60);
    lv_obj_set_y(ui_TextArea7, -28);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea7, 4);
    lv_textarea_set_placeholder_text(ui_TextArea7, "0 to 20mS");



    ui_Label19 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 76);
    lv_obj_set_y(ui_Label19, -28);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Off Time");

    ui_TextArea8 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea8, 100);
    lv_obj_set_height(ui_TextArea8, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_TextArea8, 177);
    lv_obj_set_y(ui_TextArea8, -28);
    lv_obj_set_align(ui_TextArea8, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea8, 4);
    lv_textarea_set_placeholder_text(ui_TextArea8, "0 to 20mS");



    ui_Label20 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -183);
    lv_obj_set_y(ui_Label20, 28);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Positive Count");

    ui_TextArea9 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea9, 100);
    lv_obj_set_height(ui_TextArea9, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_TextArea9, -60);
    lv_obj_set_y(ui_TextArea9, 28);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea9, 4);
    lv_textarea_set_placeholder_text(ui_TextArea9, "0 to 20");



    ui_Label21 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 54);
    lv_obj_set_y(ui_Label21, 28);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Negative Count");

    ui_TextArea10 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea10, 100);
    lv_obj_set_height(ui_TextArea10, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_TextArea10, 177);
    lv_obj_set_y(ui_TextArea10, 28);
    lv_obj_set_align(ui_TextArea10, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea10, 4);
    lv_textarea_set_placeholder_text(ui_TextArea10, "0 to 20");



    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Timing");
    lv_obj_set_flex_flow(ui_TabPage3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabPage3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabPage3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_radius(ui_TabPage3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabPage3, lv_color_hex(0x5D97FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabPage3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_TabPage3);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 507);
    lv_obj_set_height(ui_Container15, 43);
    lv_obj_set_x(ui_Container15, -61);
    lv_obj_set_y(ui_Container15, -5);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container16 = ui_Container1_create(ui_Container15);
    lv_obj_set_x(ui_Container16, -150);
    lv_obj_set_y(ui_Container16, -62);

    lv_label_set_text(ui_comp_get_child(ui_Container16, UI_COMP_CONTAINER1_LABEL1), "Delay HV ");

    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Container16, UI_COMP_CONTAINER1_TEXTAREA1), "0 to 20mS");



    ui_Container17 = ui_Container1_create(ui_Container15);
    lv_obj_set_x(ui_Container17, -151);
    lv_obj_set_y(ui_Container17, -62);

    lv_label_set_text(ui_comp_get_child(ui_Container17, UI_COMP_CONTAINER1_LABEL1), "Delay LV");

    lv_textarea_set_max_length(ui_comp_get_child(ui_Container17, UI_COMP_CONTAINER1_TEXTAREA1), 2);
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Container17, UI_COMP_CONTAINER1_TEXTAREA1), "0 to 20mS");



    ui_Container18 = ui_Container1_create(ui_TabPage3);
    lv_obj_set_x(ui_Container18, -151);
    lv_obj_set_y(ui_Container18, -62);

    lv_label_set_text(ui_comp_get_child(ui_Container18, UI_COMP_CONTAINER1_LABEL1), "Delay HL");

    lv_textarea_set_max_length(ui_comp_get_child(ui_Container18, UI_COMP_CONTAINER1_TEXTAREA1), 2);
    lv_textarea_set_placeholder_text(ui_comp_get_child(ui_Container18, UI_COMP_CONTAINER1_TEXTAREA1), "0 to 20mS");



    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "More");
    lv_obj_clear_flag(ui_TabPage4, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_radius(ui_TabPage4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabPage4, lv_color_hex(0x64E7F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabPage4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    Numpad_Init();

    ui_Label13 = lv_label_create(ui_Run);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -190);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "");

    ui_ImgButton2 = lv_imgbtn_create(ui_Run);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_play_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 51);
    lv_obj_set_height(ui_ImgButton2, 51);
    lv_obj_set_x(ui_ImgButton2, 226);
    lv_obj_set_y(ui_ImgButton2, -139);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_ImgButton1 = lv_imgbtn_create(ui_Run);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_pause_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_pause_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 51);
    lv_obj_set_height(ui_ImgButton1, 51);
    lv_obj_set_x(ui_ImgButton1, 291);
    lv_obj_set_y(ui_ImgButton1, -139);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_ImgButton1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton3 = lv_imgbtn_create(ui_Run);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_run_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_run_png, NULL);
    lv_obj_set_width(ui_ImgButton3, 51);
    lv_obj_set_height(ui_ImgButton3, 51);
    lv_obj_set_x(ui_ImgButton3, 357);
    lv_obj_set_y(ui_ImgButton3, -139);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_ImgButton3, lv_color_hex(0xEC0202), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_ImgButton3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container3 = lv_obj_create(ui_Run);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 574);
    lv_obj_set_height(ui_Container3, 268);
    lv_obj_set_x(ui_Container3, -101);
    lv_obj_set_y(ui_Container3, -37);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Run);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 774);
    lv_obj_set_height(ui_Container9, 50);
    lv_obj_set_x(ui_Container9, -1);
    lv_obj_set_y(ui_Container9, -207);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container9, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -298);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Sequence ");

    ui_Dropdown1 = lv_dropdown_create(ui_Container9);
    lv_dropdown_set_options(ui_Dropdown1, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20");
    lv_obj_set_width(ui_Dropdown1, 59);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -226);
    lv_obj_set_y(ui_Dropdown1, 0);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_Dropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label9 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -158);
    lv_obj_set_y(ui_Label9, 0);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Positive ");

    ui_Dropdown2 = lv_dropdown_create(ui_Container9);
    lv_dropdown_set_options(ui_Dropdown2, "1\n2\n3\n4\n5\n6\n7\n8");
    lv_obj_set_width(ui_Dropdown2, 59);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, -226);
    lv_obj_set_y(ui_Dropdown2, 0);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_Dropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label10 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -158);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Negative");

    ui_Dropdown3 = lv_dropdown_create(ui_Container9);
    lv_dropdown_set_options(ui_Dropdown3, "1\n2\n3\n4\n5\n6\n7\n8");
    lv_obj_set_width(ui_Dropdown3, 59);
    lv_obj_set_height(ui_Dropdown3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown3, -226);
    lv_obj_set_y(ui_Dropdown3, 0);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_Dropdown3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label11 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -158);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "High Volt");

    ui_TextArea1 = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_TextArea1, 95);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea1, 4);
    lv_textarea_set_placeholder_text(ui_TextArea1, "0 to 300V");



    ui_Label12 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -158);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Low Volt");

    ui_TextArea2 = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_TextArea2, 95);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea2, 4);
    lv_textarea_set_placeholder_text(ui_TextArea2, "0 to 50V");



    ui_Container1 = lv_obj_create(ui_Run);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 185);
    lv_obj_set_height(ui_Container1, 198);
    lv_obj_set_x(ui_Container1, 292);
    lv_obj_set_y(ui_Container1, -2);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    Chart_Init();
    ui_Label22 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -23);
    lv_obj_set_y(ui_Label22, 0);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22,
                      "Status:\nHigh Voltage: \nLow Voltage:\nCurrent:\nEnergy:\nImpedance:\nTotal Sequece:\nTotal High Pulse:\nTotal Low Pulse:");
    lv_obj_set_style_text_letter_space(ui_Label22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label22, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label23, 109);
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 27);
    lv_obj_set_y(ui_Label23, 1);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "DISCONNECT\n---\n---\n---\n---\n---\n---\n---\n---");
    lv_obj_set_style_text_letter_space(ui_Label23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label23, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label23, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    create_sequence_buttons();
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea7, ui_event_TextArea7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea8, ui_event_TextArea8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea9, ui_event_TextArea9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea10, ui_event_TextArea10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Container16, UI_COMP_CONTAINER1_TEXTAREA1),
                        ui_event_Container16_Container16_TextAreaLV1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Container17, UI_COMP_CONTAINER1_TEXTAREA1),
                        ui_event_Container17_Container17_TextAreaLOnTime1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Container18, UI_COMP_CONTAINER1_TEXTAREA1),
                        ui_event_Container18_Container18_TextAreaLOffTime1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown3, ui_event_Dropdown3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);

}
