// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Setting_screen_init(void)
{
    ui_Setting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Setting);
    lv_img_set_src(ui_Image6, &ui_img_left_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image6, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_Image6);
    lv_obj_set_width(ui_Button3, 60);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 200);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_backed_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container20 = lv_obj_create(ui_Setting);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 268);
    lv_obj_set_height(ui_Container20, 31);
    lv_obj_set_x(ui_Container20, -141);
    lv_obj_set_y(ui_Container20, -96);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container20, LV_FLEX_FLOW_ROW_REVERSE);
    lv_obj_set_flex_align(ui_Container20, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_Container20);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Label8 = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Auto release after process");

    ui_Container21 = lv_obj_create(ui_Setting);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_width(ui_Container21, 268);
    lv_obj_set_height(ui_Container21, 31);
    lv_obj_set_x(ui_Container21, -142);
    lv_obj_set_y(ui_Container21, -135);
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Brightness");

    ui_Slider1 = lv_slider_create(ui_Container21);
    lv_slider_set_range(ui_Slider1, 20, 240);
    lv_slider_set_value(ui_Slider1, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Container28 = lv_obj_create(ui_Setting);
    lv_obj_remove_style_all(ui_Container28);
    lv_obj_set_width(ui_Container28, 268);
    lv_obj_set_height(ui_Container28, 31);
    lv_obj_set_x(ui_Container28, -141);
    lv_obj_set_y(ui_Container28, -58);
    lv_obj_set_align(ui_Container28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container28, LV_FLEX_FLOW_ROW_REVERSE);
    lv_obj_set_flex_align(ui_Container28, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch2 = lv_switch_create(ui_Container28);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Label39 = lv_label_create(ui_Container28);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Auto Sleep");

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);

}
